/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Languages } from './languages';

export class EndToEndDubbingRequestPayload {
    /**
    * The URL of the media file to be used to create the end-to-end dubbing task.
    */
    'videoUrl': string;
    /**
    * The original language of the media file to be used to create the end-to-end dubbing task.
    */
    'sourceLanguage': Languages;
    /**
    * The list of desired languages that the media file will be dubbed to.
    */
    'targetLanguages'?: Array<Languages>;
    /**
    * Optional array of one or two zero‑based audio track indices to dub. Only supported for `MXF` files. If omitted, the first audio track (index 0) is used by default.
    */
    'selectedAudioTracks'?: Array<number | null>;
    /**
    * Optional flag to append the dubbed audio as a new audio track in the output file. Only supported for `MXF` files. If `true`, the dubbed audio is added as an additional track; if `false` or omitted, the source would be returned with only dubbed audio.
    */
    'addOutputAsAnAudioTrack'?: boolean;
    /**
    * An optional list of dictionary IDs selected by the user. Each entry must be an integer corresponding to a valid dictionary ID. If provided, at least one ID is required.
    */
    'chosenDictionaries'?: Array<number>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "videoUrl",
            "baseName": "video_url",
            "type": "string"
        },
        {
            "name": "sourceLanguage",
            "baseName": "source_language",
            "type": "Languages"
        },
        {
            "name": "targetLanguages",
            "baseName": "target_languages",
            "type": "Array<Languages>"
        },
        {
            "name": "selectedAudioTracks",
            "baseName": "selected_audio_tracks",
            "type": "Array<number | null>"
        },
        {
            "name": "addOutputAsAnAudioTrack",
            "baseName": "add_output_as_an_audio_track",
            "type": "boolean"
        },
        {
            "name": "chosenDictionaries",
            "baseName": "chosen_dictionaries",
            "type": "Array<number>"
        }    ];

    static getAttributeTypeMap() {
        return EndToEndDubbingRequestPayload.attributeTypeMap;
    }
}

export namespace EndToEndDubbingRequestPayload {
}
