/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class LanguageItem {
    /**
    * The id property represents a unique numerical identifier assigned to each language in the system.
    */
    'id'?: number;
    /**
    * The language property represents the full, human-readable name of a language and its associated regional or country variant.
    */
    'language'?: string;
    /**
    * The short name is a standardized identifier for each language and locale combination, represented in the format of <language code>-<country code>.
    */
    'shortName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "string"
        },
        {
            "name": "shortName",
            "baseName": "short_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return LanguageItem.attributeTypeMap;
    }
}

