/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class OutputAPIKey {
    'id': number;
    'apiKey': string;
    'apiKeyName'?: string | null;
    'createdAt': Date;
    'expiryTime': Date;
    'teamId': number;
    'isValid': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "apiKey",
            "baseName": "api_key",
            "type": "string"
        },
        {
            "name": "apiKeyName",
            "baseName": "api_key_name",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "expiryTime",
            "baseName": "expiry_time",
            "type": "Date"
        },
        {
            "name": "teamId",
            "baseName": "team_id",
            "type": "number"
        },
        {
            "name": "isValid",
            "baseName": "is_valid",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return OutputAPIKey.attributeTypeMap;
    }
}

