/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DubAltFormatResponseBody } from './dubAltFormatResponseBody';
import { TaskID } from './taskID';

export class RequestDubbedOutputInAltFormat200Response {
    'outputUrl'?: any | null;
    'taskId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "outputUrl",
            "baseName": "output_url",
            "type": "any"
        },
        {
            "name": "taskId",
            "baseName": "task_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RequestDubbedOutputInAltFormat200Response.attributeTypeMap;
    }
}

