/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DialogueItem } from './dialogueItem';

export class RunInfoResponse {
    /**
    * The unique identifier for the run, which was generated during the end to end dub creation process and returned upon task completion.
    */
    'runId'?: number;
    /**
    * The URL pointing to the generated dubbed video file.
    */
    'outputVideoUrl'?: string;
    /**
    * The URL pointing to the generated dubbed audio file.
    */
    'outputAudioUrl'?: string;
    /**
    * A collection of dialogue items representing the textual transcript of the dubbed output.
    */
    'transcript'?: Array<DialogueItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "runId",
            "baseName": "run_id",
            "type": "number"
        },
        {
            "name": "outputVideoUrl",
            "baseName": "output_video_url",
            "type": "string"
        },
        {
            "name": "outputAudioUrl",
            "baseName": "output_audio_url",
            "type": "string"
        },
        {
            "name": "transcript",
            "baseName": "transcript",
            "type": "Array<DialogueItem>"
        }    ];

    static getAttributeTypeMap() {
        return RunInfoResponse.attributeTypeMap;
    }
}

