/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DialogueItem } from './dialogueItem';

export class StoryRunInfoResponse {
    /**
    * The URL pointing to the generated audio file for the story.
    */
    'audioUrl'?: string;
    /**
    * The URL pointing to the audio file that contains the story\'s dialogue.
    */
    'dialogueUrl'?: string;
    /**
    * A collection of dialogue items representing the textual transcript of the story.
    */
    'transcript'?: Array<DialogueItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "audioUrl",
            "baseName": "audio_url",
            "type": "string"
        },
        {
            "name": "dialogueUrl",
            "baseName": "dialogue_url",
            "type": "string"
        },
        {
            "name": "transcript",
            "baseName": "transcript",
            "type": "Array<DialogueItem>"
        }    ];

    static getAttributeTypeMap() {
        return StoryRunInfoResponse.attributeTypeMap;
    }
}

