/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TranslationResult {
    /**
    * An array of strings containing the translated output texts. Each item in the array corresponds to one translated text
    */
    'texts'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "texts",
            "baseName": "texts",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return TranslationResult.attributeTypeMap;
    }
}

