/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum TTSStreamOutputFormat {
    Wav = <any> 'wav',
    Flac = <any> 'flac',
    Adts = <any> 'adts',
    PcmS16le = <any> 'pcm_s16le',
    PcmS32le = <any> 'pcm_s32le'
}
