// This file was auto-generated by Fern from our API Definition.

import type { SubtitleResult } from "./SubtitleResult.js";
import type { TranscriptExportResult } from "./TranscriptExportResult.js";

export type SubtitleResultResponse =
    | SubtitleResult
    | TranscriptExportResult
    | Record<string, SubtitleResult | TranscriptExportResult>;
