// This file was auto-generated by Fern from our API Definition.

export interface SubtitleFormattingOptions {
    max_segment_duration_in_seconds?: number;
    min_segment_duration_in_seconds?: number;
    max_characters_in_segment?: number;
    max_reading_speed_in_cps?: number;
    min_gap_between_segments_in_frames?: number;
}
