// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         run_id: 1
 *     }
 */
export interface GetSubtitleResultSubResultRunIdGetRequest {
    run_id: number | null;
    /** Format to use for the subtitle. Either `srt`, `vtt` or `txt`. Defaults to `txt`. */
    format_type?: CambApi.TranscriptFileFormat;
    /** Data type for the subtitle being returned. Returns the raw data or a presigned url for the file. */
    data_type?: CambApi.TranscriptDataType;
}
