// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         body: {
 *             run_ids: [1]
 *         }
 *     }
 */
export interface GetSubtitleResultsSubResultsPostRequest {
    body: CambApi.RunIDsRequestPayload;
    traceparent?: string | null;
    /** Format to use for the subtitles. Either `srt`, `vtt` or `txt`. Defaults to `txt`. */
    format_type?: CambApi.TranscriptFileFormat;
    /** Data type for the subtitles being returned. Returns the raw data or presigned urls for the files. */
    data_type?: CambApi.TranscriptDataType;
}
